version: '3'
services:
  database:
    image: plantei-database
    hostname: database
    container_name: plantei-database
    build:
      context: .
      dockerfile: ./docker/Dockerfile_postgres
    restart: always
    env_file:
      - ./docker/db_credentials.env
  plantei:
    image: plantei-backend
    hostname: plantei
    container_name: plantei-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile_plantei
    ports:
      - 8080:8080
    depends_on:
      - database
