version: '3.8'
services:

  database:

    image: plantei-database:1.0
    user: "postgres"
    hostname: database
    container_name: plantei-database
    restart: always

    build:
      context: docker
      dockerfile: Dockerfile.postgres

    networks:
      - back

    expose:
      - '5432'

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
       test: [ "CMD", "pg_isready", "--dbname=${POSTGRES_DB}", "--username=${POSTGRES_USER}" ]
       interval: 5s
       timeout: 5s
       retries: 5

  plantei:

    depends_on:
      - database

    image: plantei-backend:1.0
    hostname: plantei
    container_name: plantei-backend

    build:
      context: .
      dockerfile: docker/Dockerfile.plantei

    networks:
      - back

    ports:
      - 8080:8080

#    read_only: true
#    tmpfs:
#      - /bin
#      - /boot
#      - /etc
#      - /home
#      - /lib
#      - /mnt
#      - /opt
#      - /root
#      - /run
#      - /sbin
#      - /server
#      - /srv
#      - /sys
#      - /tmp
#      - /usr
#      - /var

networks:
  back:
    driver: bridge

volumes:
  postgres:
