version: '3.8'
services:

  frontend:
    hostname: frontend
    image: plantei-frontend:1.0
    container_name: plantei-frontend
    build:
      context: plantei-frontend
      dockerfile: Dockerfile

#    deploy:
#      resources:
#        limits:
#          memory: 200M
#        reservations:
#          memory: 10M
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s

#    user: "nginx"
    restart: always
#    cap_drop: [ "ALL" ]

#    environment:
#      - NODE_ENV=production
#      - NODE_CONFIG_LOGLEVEL=debug
#      - NPM_CONFIG_PREFIX=/home/getby/.npm-global

    networks: [ "front" ]
    ports: [ "80:80" ]

  database:
    hostname: database
    container_name: plantei-database
    image: plantei-database:1.0
    build:
      context: database
      dockerfile: Dockerfile
    stop_signal: SIGINT

    deploy:
      resources:
        limits:
          memory: 200M
          pids: 30
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    user: "postgres"
    restart: unless-stopped
    cap_drop: [ "ALL" ]

    environment:
      - POSTGRES_DB_FILE=${POSTGRES_DB_FILE:?err}
      - POSTGRES_USER_FILE=${POSTGRES_USER_FILE:?err}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE:?err}
      - LANG="pt_BR.UTF-8"

    volumes:
      - postgres_db:/var/lib/postgresql/data:rw

    secrets:
      - source: postgres_db
        target: postgres_db
        mode: 0440
      - source: postgres_user
        target: postgres_user
        mode: 0440
      - source: postgres_passwd
        target: postgres_passwd
        mode: 0440

    networks: [ "back" ]
    expose: [ "5432" ]

    read_only: true
    tmpfs: [ "/var/run/postgresql" ]

    healthcheck:
       test: pg_isready --dbname=$$(cat ${POSTGRES_DB_FILE:?err}) --username=$$(cat ${POSTGRES_USER_FILE:?err})
       interval: 5s
       timeout: 5s
       retries: 5

  backend:
    hostname: backend
    container_name: plantei-backend
    image: plantei-backend:1.0
    build:
      context: .
      dockerfile: plantei-backend/Dockerfile
    stop_signal: SIGINT

    deploy:
      resources:
        limits:
          memory: 1G
          pids: 40
        reservations:
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    restart: always
    cap_drop: [ "ALL" ]

    networks: [ "back" ]
    ports: [ "8080:8080/tcp" ]

    read_only: true
    tmpfs: [ "/tmp" ]

    depends_on:
      database:
        condition: service_healthy

networks:
  back:
    name: plantei-backend
    driver: bridge
  front:
    name: plantei-frontend
    driver: bridge

volumes:
  postgres_db:
    name: plantei-db

secrets:
  postgres_db:
    file: ./database/postgres-db.txt
  postgres_user:
    file: ./database/postgres-user.txt
  postgres_passwd:
    file: ./database/postgres-passwd.txt
